language: python
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  #- "3.7-dev"
before_install:
  - pip install pip -U
  - pip install -r requirements.txt -U
  - pip install -r optional-requirements.txt -U
install:
  - travis_retry pip install -e .
script: 
  #- travis_wait ./run_tests.py
  #- travis_wait python run_tests.py
  - travis_wait pytest -p no:doctest --cov-config .coveragerc --cov-report html --xdoctest --cov=ubelt --network ubelt
after_success: 
  #- coveralls || echo "Coveralls upload failed"
  - codecov 
#after_failure: 
#  - cat failed_doctests.txt
cache: 
    apt: true
    directories:
        - $HOME/.pip-cache
