language: python
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download
python:
  - "2.7"
  - "3.5"
  - "3.6"
  #- "3.7"
before_install:
  - pip install pip -U
  - pip install -r requirements/tests.txt -U
  - pip install -r requirements/runtime.txt -U
  - pip install -r requirements/optional.txt -U
install:
  - travis_retry pip install -e .
script: 
  - travis_wait ./run_tests.py --network
after_success: 
  - codecov 
cache: 
    apt: true
    directories:
        - $HOME/.pip-cache
